edition: 1.0.0
name: transform_fun
access: default
vars:
  region: cn-shenzhen
services:
  fc-customruntime-mark:
    component: devsapp/fc
    actions:
      pre-deploy:
        - run: s build --use-docker && docker push registry.cn-shenzhen.aliyuncs.com/stevie/fc -a
    props:
      region: ${vars.region}
      service:
        name: customruntime
        description: helloworld
        internetAccess: true
      function:
        name: mark
        handler: index.handler
        timeout: 3
        memorySize: 128
        runtime: custom-container
        customContainerConfig:
          image: registry.cn-shenzhen.aliyuncs.com/stevie/fc:mark
        instanceConcurrency: 100
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - HEAD
              - POST
              - PUT
              - GET
              - DELETE
      customDomains:
        - domainName: mark.fc-hn.stevie.top
          protocol: HTTP
          routeConfigs:
            - serviceName: customruntime
              functionName: mark
              path: /*
